In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
data=pd.read_csv('Breast Cancer.csv')

In [6]:
print (data.head(5))

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_wor

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [8]:
data.diagnosis = [1 if each == "M" else 0 for each in data.diagnosis]

In [9]:
y = data.diagnosis.values
x_data = data.drop(['diagnosis'], axis = 1)


In [10]:
x = (x_data - np.min(x_data))/(np.max(x_data) - np.min(x_data)).values

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.max(axis=None) will return a scalar max over the entire DataFrame. To retain the old behavior, use 'frame.max(axis=0)' or just 'frame.max()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.15, random_state = 42)


In [12]:
x_train

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
9    0.092715     0.259312      0.484613        0.277659   0.140997   
468  0.009991     0.502579      0.460602        0.519729   0.355037   
382  0.000090     0.239907      0.439973        0.241587   0.129077   
322  0.000972     0.278243      0.122083        0.269712   0.153256   
84   0.009441     0.237541      0.200879        0.229148   0.127169   
..        ...          ...           ...             ...        ...   
71   0.000934     0.090255      0.166723        0.103656   0.042630   
106  0.000938     0.220503      0.291512        0.216847   0.114104   
270  0.009768     0.345923      0.240446        0.321401   0.207466   
435  0.000987     0.331251      0.335137        0.327068   0.193425   
102  0.000937     0.246060      0.365573        0.231014   0.133701   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
9           0.595558          0.675480        0.532568             0.424602   
468         0.363456          0.555242        0.500469             0.498012   
382         0.150943          0.269677        0.186106             0.148012   
322         0.548614          0.211521        0.089035             0.168986   
84          0.402636          0.160328        0.097259             0.092594   
..               ...               ...             ...                  ...   
71          0.408053          0.410159        0.201640             0.142744   
106         0.555836          0.252500        0.165651             0.173211   
270         0.105263          0.022606        0.016987             0.031064   
435         0.481809          0.288080        0.263824             0.321223   
102         0.248262          0.064413        0.055834             0.087972   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
9         0.489899  ...      0.254714       0.763859         0.235271   
468       0.321212  ...      0.485237       0.449094         0.464117   
382       0.072222  ...      0.165066       0.444829         0.184023   
322       0.243939  ...      0.217360       0.241471         0.211116   
84        0.514646  ...      0.204198       0.343284         0.186115   
..             ...  ...           ...            ...              ...   
71        0.425253  ...      0.064141       0.097281         0.060511   
106       0.374242  ...      0.185343       0.459488         0.174810   
270       0.226263  ...      0.248310       0.230011         0.219284   
435       0.307576  ...      0.324084       0.500533         0.316201   
102       0.342929  ...      0.192458       0.554904         0.170178   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
9      0.129326          0.753682           1.000000         0.882588   
468    0.307658          0.327082           0.437766         0.412540   
382    0.074518          0.111074           0.285347         0.232588   
322    0.101824          0.551608           0.189976         0.143051   
84     0.094057          0.439345           0.167855         0.181070   
..          ...               ...                ...              ...   
71     0.024381          0.327082           0.209865         0.114537   
106    0.082703          0.644720           0.231598         0.229473   
270    0.122739          0.095754           0.022383         0.030879   
435    0.168133          0.595192           0.319692         0.325000   
102    0.089117          0.271611           0.059503         0.091454   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
9                0.759450        0.552139                 1.000000  
468              0.685911        0.145082                 0.441821  
382              0.375258        0.123398                 0.252197  
322              0.396907        0.161049                 0.199987  
84               0.262268        0.357579                 0.158730  
..                    ...             ...

In [13]:
import sklearn
from sklearn.linear_model import LogisticRegression


In [14]:
model=LogisticRegression()

In [15]:
model.fit(x_train,y_train)

LogisticRegression()

In [16]:
y_predict=model.predict(x_test)
y_pred=y_predict[:10]



In [17]:
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [18]:
y_test[:10]

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])

In [19]:
matrix = sklearn.metrics.confusion_matrix(y_test[:10], y_pred)

In [20]:
matrix = np.flip(matrix)
print("Confusion Matrix: \n", matrix)
accuracy = (matrix[0][0] + matrix[-1][-1]) / np.sum(matrix)
print(accuracy)



Confusion Matrix: 
 [[5 0]
 [0 5]]
1.0
